apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-app
  labels:
    app: developer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: developer-app
  template:
    metadata:
      labels:
        app: developer-app
    spec:
      containers:
        - name: developer-app
          image: zandergt/developer-app:latest
          ports:
            - containerPort: 3000
