apiVersion: v1
kind: Service
metadata:
  name: developer-app
  namespace: resume-website
spec:
  selector:
    app: developer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
